# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=20)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('a', 'Private'), ('b', 'Government'), ('c', 'Semi-Private'), ('d', 'Other')], max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together=set([('name', 'address')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Hospital'),
        ),
        migrations.AddField(
            model_name='disease',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Doctor'),
        ),
        migrations.AddField(
            model_name='disease',
            name='h_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set([('username', 'license_number')]),
        ),
    ]
