# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('a', 'Private'), ('b', 'Government'), ('c', 'Semi-Private'), ('d', 'Other')], max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together=set([('name', 'address')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set([('username', 'license_number')]),
        ),
    ]
