# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
