# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=20)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Doctor')),
                ('h_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Hospital')),
            ],
        ),
    ]
