# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0003_auto_20171008_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='society',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.Society'),
        ),
        migrations.AlterField(
            model_name='studentadmin',
            name='enroll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
    ]
