# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20171008_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.AddField(
            model_name='college',
            name='college_id',
            field=models.CharField(default='1', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='society',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.Society'),
        ),
        migrations.AlterField(
            model_name='studentadmin',
            name='enroll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
    ]
