# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_auto_20171008_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
        migrations.AlterField(
            model_name='society',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.Society'),
        ),
        migrations.AlterField(
            model_name='studentadmin',
            name='enroll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('name', 'event')]),
        ),
    ]
