# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_auto_20171009_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society',
            old_name='field',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='society',
            old_name='s_name',
            new_name='society_name',
        ),
        migrations.AddField(
            model_name='society',
            name='facebook_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='society',
            name='website',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
        migrations.AlterField(
            model_name='society',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.Society'),
        ),
        migrations.AlterField(
            model_name='studentadmin',
            name='enroll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='society',
            unique_together=set([('college', 'society_name')]),
        ),
    ]
